debug: true
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:20001/eureka/
    instance:
        metadataMap:
             instanceId: ${spring.application.name}:${random.value}
        preferIpAddress: true
feign:
    httpclient:
        connection-timeout: 3000000
        time-to-live: 3000000
        time-to-live-unit: SECONDS
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
server:
    port: 9001
spring:
    rabbitmq:
        host: 127.0.0.1
        password: panmin1W
        port: 5672
        username: wangzhe
    application:
        name: serversidetest
    jpa:
        hibernate:
          ddl-auto: validate
        show-sql: true
    datasource:
        maxPoolPreparedStatementPerConnectionSize: 20
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        initialSize: 1
        maxActive: 20
        maxOpenPreparedStatements: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 1
        name: root
        password: panmin1W
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:20005/serversizetest
        username: root
        validationQuery: select 'x'
        dbcp2:                                          # 进行数据库连接池的配置
            min-idle: 5                                   # 数据库连接池的最小维持连接数
            initial-size: 5                               # 初始化提供的连接数
            max-total: 5                                  # 最大的连接数
            max-wait-millis: 200                          # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: main.domain          # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
         classpath:mybatis/mapper/**/*.xml